### ISSUE TITLE
outdated lodash - improving performance

### ISSUE THREAD

**Issue by igorlino** [jas/gulp-preprocess#12]
There is a newer version of lodash (3.3.1) which  improved performance 20-40% overall  by better utilizing the JIT in JavaScript engines, using internal helper functions that avoid optimization disqualifications & increase the likelihood of function inlining.

lodash 3.0.0 is 40%  (1.40x) faster than lodash 2.4.1.

In v3 also introduced were lazily evaluated chaining for massive performance wins in certain scenarios.

Any change to update to the latest release?

**Comment by Sirlon** [comment]
+1

**Comment by SgtPooki** [comment]
+1. It shouldn't take much to try to upgrade and fix the 3 places it's used. If this is still hanging around by the time I see it again, I will submit a PR.

**Comment by ioloie** [comment]
I've submitted https://github.com/jas/gulp-preprocess/pull/21 for this issue.

**Comment by igorlino** [comment]
Thanks :+1:
