### ISSUE TITLE
Doesn't work with Jade

### ISSUE THREAD

**Issue by BrunoKinoshita** [jas/gulp-preprocess#14]

**Comment by jas** [comment]
`gulp-preprocess` is basically a wrapper around the [`preprocess`](https://github.com/jsoverson/preprocess) module. That module is where support for specific extensions and file types is located. Please open an issue or create a pull request there if you need automatic support for a specific comment syntax.

Alternatively, you can try using the [`extension` option](https://github.com/jas/gulp-preprocess#optionsextension), setting this to `"js"` (e.g, `//`) or `"html"` (e.g., `<!-- -->`) depending on the comment style you use in your Jade files.

I'll be happy to update the version of `preprocess` that this module uses if it is updated with built-in support for Jade files.

**Comment by zhekaus** [comment]
I can't make it work with .jade
extension and type option doens't work

**Comment by asoesilo** [comment]
Setting the `extension` option to `'html'` works for me.

Then I can do something like the following in the my .jade file:
```
script.
  // @if ENV='dev'
  var env = '<!-- @echo ENV -->'
  console.log('env', env);
  // @endif
```
