### ISSUE TITLE
Upgrade to latest preprocess

### ISSUE THREAD

**Issue by gittycat** [jas/gulp-preprocess#16]
Could you upgrade to the latest preprocess ~2.3.1
It has Jade support and fixes.

Thanks for the great work.

**Comment by dogancelik** [comment]
Latest version is now `3.0.2`

**Comment by jnath** [comment]
Hello, 
it is possible to merge this pr https://github.com/jas/gulp-preprocess/pull/18
and publish to npm please ?

**Comment by oyevtushok** [comment]
+1

**Comment by danizep** [comment]
Upgrade please...

**Comment by icek** [comment]
+1

**Comment by jhtep** [comment]
+1, I had to create a fork to patch package.json to Upgrade to "preprocess": "2.3.1" for @exec multi arg fix. I am not familiar with testing enough to update to most recent version of preprocess, but this would be ideal.

**Comment by ioloie** [comment]
As it stands, preprocess has had a major update to version 3.0.0 so this library is starting to fall pretty far behind

**Comment by jas** [comment]
Unfortunately I'm unable to continue maintaining this module. If anyone would like to help, please let me know.

**Comment by ioloie** [comment]
I would be willing to help alright. The amount of time fixing this issue alone would save me (I really want the recursive includes from preprocess 3.x) would be less than the time I would probably spend maintaining it.

**Comment by jas** [comment]
@ioloie Thank you. I've given you push access to the repository, and can give you permissions for the package on npm as well (I'll need your npm username).

**Comment by ioloie** [comment]
@jas, It's https://www.npmjs.com/~ioloie

**Comment by jas** [comment]
@ioloie You can now publish the package to npm. Thank you!
